apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: forward-host
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        name: http.80
    patch:
      operation: MERGE
      value:
        route:
          host_rewrite_header: x-forwarded-host
  workloadSelector:
    labels:
      app: istio-ingressgateway